### ISSUE TITLE
add. roblox windows 10

### ISSUE THREAD

**Issue by demo308** [prik-k/awesome-OS#18]
do it because yes https://www.roblox.com/games/7848359510/Windows-10-OS-Operating-System-SIM

**Comment by zriyansh** [comment]
create a PR for it, will merge @demo308

**Comment by demo308** [comment]
i found some more on https://justforfun.io/ like https://github.com/EddyVinck/xp

**Comment by demo308** [comment]
Retrobar

**Comment by demo308** [comment]
https://simone.computer/#/webdesktops

**Comment by demo308** [comment]
https://scratch.mit.edu/projects/118579301/
