### ISSUE TITLE
Original repo name

### ISSUE THREAD

**Issue by khang-nd** [prik-k/awesome-OS#6]
I would suggest keeping the original name of the repos:

- win98.css -> 98.css
- winxp.css -> XP.css
- win7.css -> 7.css
- ... (any other repos that you changed)

Reason: they are given by their authors. It's their decision to be respected.

**Comment by prik-k** [comment]
sure thing if you say, my main motive of changing them was just to make it more understandable by their names. 

I will change them asap.

**Comment by khang-nd** [comment]
Thank you, I believe the description you put is good enough to let people know. Hope I didn't sound harsh and thanks for your effort in gathering these cool projects.
